# permissions for end users to view configs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: config-viewer-role
rules:
- apiGroups:
  - universal-api-controller.io.universal-api-controller.io
  resources:
  - configs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - universal-api-controller.io.universal-api-controller.io
  resources:
  - configs/status
  verbs:
  - get
