# permissions for end users to view endpointtemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: endpointtemplate-viewer-role
rules:
- apiGroups:
  - universal-api-controller.io.universal-api-controller.io
  resources:
  - endpointtemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - universal-api-controller.io.universal-api-controller.io
  resources:
  - endpointtemplates/status
  verbs:
  - get
