---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - universal-api-controller.io
  resources:
  - configTemplates
  verbs:
  - get
- apiGroups:
  - universal-api-controller.io
  resources:
  - configs
  verbs:
  - get
- apiGroups:
  - universal-api-controller.io
  resources:
  - configs/finalizers
  verbs:
  - update
- apiGroups:
  - universal-api-controller.io
  resources:
  - configs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - universal-api-controller.io
  resources:
  - endpointTemplates
  verbs:
  - get
- apiGroups:
  - universal-api-controller.io
  resources:
  - functions
  verbs:
  - get
