apiVersion: universal-api-controller.io/v1alpha1
kind: Function
metadata:
  name: function-sample
spec:
  params:
    - name: host
      description: Host to Configure(Can be Cluster intern or extern)
    - name: port
      description: Port of the API
  actions:
    - name: create
      ref:
        name: endpointtemplate-sample
        kind: EndpointTemplate
      params:
        - name: host
          value: {{ .Parameters.host }}
        - name: port
          value: "{{ .Parameters.port }}"
