apiVersion: universal-api-controller.io/v1alpha1
kind: EndpointTemplate
metadata:
  name: endpointtemplate-sample
spec:
  params:
    - name: host
      description: Host to Configure(Can be Cluster intern or extern)
    - name: port
      description: Port of the API
  method: GET
  url: https://{{ .Parameters.host }}:{{ .Parameters.port }}/
